### PR TITLE
Add action for ci testing

### LINKED ISSUE #3: add GitHub Action for Continuous Integration testing
CI Action allows testing every time you update your code in GitHub, thus allowing you to see testing results without dev releases to CPAN for cpantesters.

PR coming momentarily

per https://perlmonks.org/?node_id=11154426
-- _pryrt_ (from perlmonks)

### PR DESCRIPTION
**Pull request by pryrt**
I got it to the point where everything was able to install dependencies and run the tests.

I'm not going to fix your code for you, so these tests will show fails on both Ubuntu and Windows.  You will want to fix either your tests or your distribution in order to get those tests to pass.

The GH Actions workflow includes some commented stuff that will help you increase your coverage to even more perl versions and systems, and even has the hints as to how to publish the "coverage" (which I think can then be integrated into coveralls.io ... I forget for sure, because my coveralls used to be linked to the now paid-only travis-ci, and I don't currently remember whether I've gotten coveralls to read from github or not....)

You can look through other of my repositories to see more examples of my CI testing, both with GitHub actions and with AppVeyor (which is what I used for Windows CI before GHActions... and still do, for some projects that I've had trouble with getting the GH Actions to work, even though it does work for AppVeyor)

closes #3

### CODE REVIEW

**Comment by pryrt** [comment]
For this one, I suggest a squash-and-merge, so that it's only one commit into your repo.  It took me a while to get everything so it properly installed dependencies including libgd

**Comment by IanBod** [comment]
Clever stuff this GH Actions!
Thanks for the PR.

From the number of commits, it seems quite a task to get the yml file working.

**Comment by pryrt** [comment]
> From the number of commits, it seems quite a task to get the yml file working.

Only because I'm not that great at Actions yet, and because I forgot that unlike on Strawberry Perl, the Linux perls don't have libgd pre-installed, so I had to figure it out

**Comment by pryrt** [comment]
Similar to what the anonymous monk recommended [here](https://perlmonks.org/?node_id=11154460), I had come up with a test that used known pixels (since the AM posted before I was quite ready to post my results, I didn't bother posting at perlmonks, but figured I'd at least ping you about it here).  

I used an image that's 3 wide and 1 tall (with three different colors) for the horizontal test, and 1 wide 3 time (three colors) for vertical tests.

I was able to get a successful [test suite](https://github.com/pryrt/Image-Square/actions/runs/6190018714) on 5.38 and 5.12, both Windows and Ubuntu.

Other improvements to the test:
- Removed huge images
- Add 3x1 and 1x3 images instead
- Stop using md5 hash
- Use simple pixel checks instead
- Use isa_ok instead of a simple ok check for instantiation checks
- Show more usage of `is` and `cmp_ok` instead of plain `ok()` checks
- during `00-load.t`, add `diag` for Perl-GD and libgd version information, to give more info akin to your Image::Square and Perl version diagnostics

I also added a dummy test-coverage printout for the runs that don't have COVERAGE set; and I confirmed that the COVERAGE=1 runs _will_ propagate the test coverage to coveralls.io -- example [top level report](https://coveralls.io/builds/62668036) and [digging into the details](https://coveralls.io/builds/62668036/source?filename=lib%2FImage%2FSquare.pm): in the details, it shows any lines of code that aren't covered by your tests.  It looks like it's primarily your error checking (which people who aren't used to aiming for 100% coverage often skip), though it also shows that you never passed in a GD-object instead of filename into the `new()` method.  (Also, shown in Devel::Cover's detailed output -- on your local machine, run `cover -test -report html` then open `cover_db\coverage.html` to see those details -- there isn't a test of `->square(0)` (ie, size is passed in, but is not >0)

(Oh, and if you don't have one yet, you can sign up for a coveralls.io account by logging in with your GitHub account.  After logging in, hit the + **Add Repos** button: it will show you all your repos, and you can toggle the slider on **Image::Square** to enable that.  Then, any time you push to github when your GitHubAction has the `include: ... COVERAGE=1` section uncommented, the GH Action will automatically send the results to coveralls, like you saw in my example coveralls link.)

I didn't do another PR from my [branch that implemented my test fixes](https://github.com/pryrt/Image-Square/tree/myTests), because I think it might help you learn some of these testing concepts by trying to re-implement them from this high-level description, rather than just blindly accepting my code.  Though there's nothing that is stopping you from just copy/pasting from my branch if you really wanted to, or asking nicely for a PR)

Good luck.

**Comment by IanBod** [comment]
Thank you.  I appreciate your help and that you did not make the PR.  That's definitely better for my learning :)

The issue I have with removing the big images is that when put to use, the module will be used on large, potentially huge, images.  So I feel that the tests should reflect that.  Perhaps I will raise that on PM so that others can chip in with their thoughts and people will come across the discussion in future.

I shall have a go at replicating your tests over the weekend.

The latest version of [02-image.t](https://github.com/IanBod/Image-Square/blob/main/t/02-image.t) does use `cmp_ok` for the comparisons.  I guess that was updated after you forked the repo.

**Pull request merged**
